# Generated by Django 5.1.3 on 2024-12-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customUser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="photo_profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/profile_pics/"
            ),
        ),
    ]
