# Generated by Django 5.1.3 on 2025-02-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0002_alter_customuser_photo_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='matricula',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
