# Generated by Django 5.1.3 on 2025-02-09 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0002_customuser_coursename_customuser_meatname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='courseName',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='meatName',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='semesterName',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='themeName',
            new_name='subject',
        ),
    ]
