# Generated by Django 5.1.3 on 2024-12-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0003_alter_customuser_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nickName',
            new_name='name',
        ),
    ]
