# Generated by Django 5.1.3 on 2025-02-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_banner'),
        ('customUser', '0003_rename_coursename_customuser_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='community_ids',
            field=models.ManyToManyField(blank=True, related_name='members', to='community.community'),
        ),
    ]
