# Generated by Django 5.1.3 on 2025-01-27 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0003_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nickName',
        ),
    ]
