# Generated by Django 5.1.3 on 2025-02-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0003_customuser_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nickName',
        ),
    ]
