# Generated by Django 5.1.3 on 2025-02-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0004_customuser_community_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
