# Generated by Django 5.1.3 on 2024-12-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0004_rename_nickname_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
