# Generated by Django 5.1.3 on 2024-12-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0005_alter_customuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='nickName',
        ),
    ]
