# Generated by Django 5.1.3 on 2024-12-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='author_username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
