# Generated by Django 5.1.3 on 2025-02-02 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_username',
        ),
    ]
