# Generated by Django 5.1.3 on 2025-02-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_user_post_user_remove_post_author_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
