# Generated by Django 5.1.3 on 2025-01-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/banners/'),
        ),
    ]
