# Generated by Django 5.1.3 on 2024-12-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_subcommunity',
            field=models.BooleanField(default=False),
        ),
    ]
