# Generated by Django 5.1.3 on 2024-12-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_community_is_subcommunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='visibility_students',
        ),
        migrations.RemoveField(
            model_name='community',
            name='visibility_teachers',
        ),
        migrations.AddField(
            model_name='community',
            name='visibility',
            field=models.CharField(default='', max_length=100),
        ),
    ]
