# Generated by Django 5.1.3 on 2024-12-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_remove_community_visibility_students_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='description',
            new_name='communityDescription',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='name',
            new_name='communityName',
        ),
        migrations.AddField(
            model_name='community',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='passwordRequired',
            field=models.BooleanField(default=False),
        ),
    ]
