# Generated by Django 5.1.3 on 2024-12-31 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_rename_description_community_communitydescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='banner',
        ),
    ]
